### ISSUE TITLE
Buggy on Firefox 53/Windows

### ISSUE THREAD

**Issue by qgustavor** [dli/paint#1]
Some strange glitches appear when painting, often coming from some edge then erasing, or blurring what was painted:

![Image showing the bug](https://i.imgur.com/k6y5ave.png)

I tried to paint a RGB, then when I finished the G the R was erased, then when I finished the B the G got blurred, erasing the B, finally I painted the R, and the B again again.

I did the same in a Blink based browser and no glitches appeared. In both browsers hardware acceleration is disabled.

**Comment by dli** [comment]
Thanks for reporting this!

I just pushed a fix. Would you mind checking that it works for you now?

**Comment by qgustavor** [comment]
I just tested, seems it's working without any issue now.
