### ISSUE TITLE
Lock sides/prevent resizing OR don't erase after resizing

### ISSUE THREAD

**Issue by vekien** [dli/paint#8]
This is an amazing little tool, however countless times I would be working on something near the edge and accidentally grab the side and pull the size of the frame in, only to loose my entire paint! 

Maybe a little checkbox that prevents edges from being resized and locks in the size of the frame.

**Comment by dli** [comment]
Does the new undo functionality adequately solve this for you? Trying to keep the interface as simple as I can!

**Comment by vekien** [comment]
Yup it does, solves and then some! Great work!!
